import json, re


name_list = [
    "Guacodile",
    "Chimney Sweep",
    "Conga Zombie (G)",
    "Tennis Champ",
    "Conehead",
    "All-Star Zombie",
    "Smashing Pumpkin",
    "Navy Bean",
    "Pismashio",
    "Peashooter",
    "Squash",
    "Bungee Plumber (T)",
    "NA1",
    "NA2",
    "Monster Mash (T)",
    "NA3",
    "NA4",
    "Sour Grapes",
    "Cabbage-pult",
    "Grow-shroom",
    "Berry Angry",
    "Medic",
    "Fishy Imp",
    "The Chickening (T)",
    "Precision Blast",
    "Slammin' Smackdown",
    "Carried Away",
    "Imp",
    "Sea-Shroom",
    "Smoosh-Shroom",
    "Bonk Choy",
    "Vanilla",
    "Bluesberry",
    "NA5",
    "Zapricot",
    "Berry Blast",
    "Storm Front",
    "Meteor Strike",
    "Fire Peashooter",
    "Flourish",
    "Fertilize",
    "Embiggen",
    "Skyshooter",
    "Holo-Flora",
    "Cattail",
    "2nd-Best Taco of All Time",
    "Weed Whack",
    "Scorched Earth",
    "Cell Phone Zombie",
    "Zombie",
    "Fun-Dead Raiser (T)",
    "Drum Major",
    "Kite Flyer (G)",
    "Landscaper (G)",
    "Rock Wall",
    "Heroic Health",
    "Terrify (T)",
    "Snorkel Zombie",
    "Vitamin Z (T)",
    "Locust Swarm (T)",
    "Cat Lady",
    "Dolphin Rider",
    "Galvanize",
    "Nibble (T)",
    "Deep Sea Gargantuar",
    "Zombot 1000 (G)",
    "Cuckoo Zombie",
    "Electrobolt",
    "Brute Strength",
    "Cakesplosion (T)",
    "Walrus Rider",
    "Uncrackable",
    "Blazing Bark",
    "Shrink Ray",
    "Sunburn",
    "Admiral Navy Bean",
    "Wall-Nut",
    "Cactus",
    "Steel Magnolia",
    "Jugger-Nut",
    "Smackadamia",
    "Poppin' Poppies",
    "Hibernating Beary",
    "Potato Mine",
    "NA6",
    "Bubble Up",
    "Grave Buster",
    "Water Chestnut",
    "Sting Bean",
    "Pea-Nut",
    "Prickly Pear",
    "Spineapple",
    "NA7",
    "Soul Patch",
    "Wall-Nut Bowling",
    "Nut Signal",
    "Shroom for Two",
    "Mushroom Ringleader",
    "Poison Ivy",
    "Buff-Shroom",
    "Petal-Morphosis",
    "Cherry Bomb",
    "Wild Berry",
    "Pair of Pears",
    "Poison Mushroom",
    "Sizzle",
    "Seedling",
    "Grapes of Wrath",
    "Sergeant Strongberry",
    "Pineclone",
    "Cornucopia",
    "NA8",
    "Repeater",
    "Torchwood",
    "Super-Phat Beets",
    "Pea Pod",
    "Party Thyme",
    "Plant Food",
    "Sweet Potato",
    "Re-Peat Moss",
    "NA9",
    "Black-Eyed Pea",
    "Potted Powerhouse",
    "Morning Glory",
    "Doubled Mint",
    "Bananasaurus Rex",
    "Jumping Bean",
    "Chilly Pepper",
    "Spring Bean",
    "Rescue Radish",
    "Snowdrop",
    "Carrotillery",
    "Threepeater",
    "Winter Squash",
    "Big Chill",
    "Whirlwind",
    "Snow Pea",
    "Shellery",
    "Fume-Shroom",
    "Iceberg Lettuce",
    "Bean Counter",
    "Brainana",
    "Winter Melon",
    "NA10",
    "Snapdragon",
    "Transmogrify",
    "Sunflower",
    "Sage Sage",
    "Mixed Nuts",
    "Bloomerang",
    "Power Flower",
    "Venus Flytrap",
    "Pepper M.D.",
    "Metal Petal Sunflower",
    "Geyser",
    "Muscle Sprout",
    "Twin Sunflower",
    "Laser Bean",
    "Lawnmower",
    "Chomoper",
    "Magnifying Grass",
    "NA11",
    "Briar Rose",
    "Dandy Lion King",
    "Three-Headed Chomper",
    "Space Cadet",
    "Electrician (G)",
    "Paparazzi Zombie",
    "Pool Shark",
    "Gadget Scientist",
    "Rocket Science (T)",
    "Cut Down to Size",
    "NA12",
    "Zombot Drone Engineer (G)",
    "Brain Vendor",
    "Copter Commando",
    "Lurch for Lunch (T)",
    "Wizard Gargantuar",
    "NA13",
    "Mad Chemist (G)",
    "Trickster",
    "Shieldcrusher Viking",
    "NA14",
    "NA15",
    "Evaporate",
    "Arm Wrestler",
    "Sumo Wrestler (G)",
    "Power Pummel",
    "Rolling Stone (T)",
    "Zombie Coach",
    "Flag Zombie",
    "NA16",
    "Buckethead",
    "Trash Can Zombie (G)",
    "Knight of the Living Dead",
    "Ra Zombie",
    "Weed Spray (T)",
    "Rodeo Gargantuar (G)",
    "Zombie King",
    "Team Mascot",
    "Undying Pharaoh",
    "Wannabe Hero",
    "Zombot's Wrath (T)",
    "Dog Walker",
    "Pied Piper (G)",
    "Haunting Zombie",
    "Smashing Gargantuar",
    "Zookeeper",
    "Coffee Zombie",
    "Acid Rain",
    "NA17",
    "NA18",
    "B-flat (T)",
    "Zombie Yeti",
    "Kangaroo Rider",
    "Nurse Gargantuar",
    "Maniacal Laugh (T)",
    "Octo Zombie",
    "Possessed",
    "Exploding Imp (G)",
    "Newspaper Zombie (G)",
    "Orchestra Conductor",
    "Flamenco Zombie",
    "Disco Zombie",
    "Imp-Throwing Gargantuar",
    "Unlife of the Party",
    "Jester (G)",
    "Foot Soldier Zombie",
    "NA19",
    "Fireworks Zombie",
    "Valkyrie",
    "NA20",
    "NA21",
    "Disco-Tron 3000 (G)",
    "Gargantuars' Feast (T)",
    "Dance Off",
    "Zombie Chicken",
    "Stealthy Imp (G)",
    "Smelly Zombie (G)",
    "Backyard Bounce (T)",
    "Imp Commander (G)",
    "Swashbuckler Zombie (G)",
    "Surprise Gargantuar (G)",
    "NA22",
    "Super Stench",
    "Dolphinado",
    "Toxic Waste Imp",
    "Pogo Bouncer (G)",
    "Line Dancing Zombie (G)",
    "Mini-Ninja",
    "Barrel Roller Zombie",
    "Mixed-Up Gravedigger (G)",
    "Tomb Raiser Zombie (G)",
    "NA23",
    "Vimpire",
    "Zombot Sharktronic Sub",
    "Zombot Plank Walker",
    "In-Crypted",
    "Hothead",
    "NA24",
    "Mush-Boom",
    "Goatify",
    "Devour",
    "Eureka",
    "Missile Madness",
    "NA25",
    "Stayin' Alive",
    "Octo-Pult",
    "Frozen Tundra",
    "Impfinity Clone",
    "Inspire",
    "Motivate",
    "Flick-a-Plant",
    "Flick-a-Zombie",
    "Get Well",
    "Rejuvenate",
    "Plumber",
    "0 PLANT CHEATS 0",
    "0 ZOMBIE CHEATS 0",
    "0 Plant Board Clear Cheat 0",
    "Lil' Buddy",
    "Pear Pal",
    "Time to Shine",
    "Espresso Fiesta",
    "Beam Me Up (T)",
    "Hail-a-Copter (T)",
    "Backup Dancer",
    "NA26",
    "Tater Toss",
    "Octo-Pet",
    "Triple Threat",
    "NA27",
    "Poison Oak",
    "Kernel Corn",
    "More Spore",
    "The Podfather",
    "Whipvine",
    "Gardening Gloves",
    "Lightning Reed",
    "Water Balloons",
    "Summoning",
    "NA28",
    "NA29",
    "Portal Technician",
    "Root Wall",
    "Loudmouth (G)",
    "Squirrel Herder (G)",
    "Aerobics Instructor",
    "Abracadaver (G)",
    "Firefighter (G)",
    "NA30",
    "Puff-Shroom",
    "Mountain Climber",
    "The Great Zucchini",
    "Doom-Shroom",
    "Mirror-Nut",
    "Gentleman Zombie (G)",
    "NA31",
    "Telepathy",
    "NA32",
    "Smoke Bomb (T)",
    "Camel Crossing (T)",
    "Headstone Carver",
    "Tough Beets",
    "NA33",
    "Weenie Beanie",
    "Barrel of Deadbeards",
    "Captain Flameface",
    "Witch's Familiar",
    "Yeti Lunchbox (T)",
    "Zom-Bats",
    "Goat",
    "Sow Magic Beans",
    "Teleport (T)",
    "0 Cheating Zombie 0",
    "Blank Plant",
    "Blank Zombie",
    "0 Zombie Board Clear Cheat 0",
    "Punish-Shroom",
    "Zombot Stomp (T)",
    "Peel Shield",
    "Haunting Ghost",
    "NA34",
    "Swabbie",
    "Magic Beanstalk",
    "Whack-a-Zombie",
    "Small-Nut",
    "Button Mushroom",
    "Bellflower",
    "Cardboard Robot Zombie",
    "Baseball Zombie",
    "Skunk Punk",
    "Hot Dog Imp",
    "NA35",
    "NA36",
    "NA37",
    "NA38",
    "NA39",
    "NA40",
    "NA41",
    "NA42",
    "NA43",
    "NA44",
    "NA45",
    "NA46",
    "NA47",
    "NA48",
    "NA49",
    "NA50",
    "NA51",
    "NA52",
    "NA53",
    "NA54",
    "NA55",
    "NA56",
    "NA57",
    "NA58",
    "NA59",
    "NA60",
    "NA61",
    "NA62",
    "NA63",
    "NA64",
    "NA65",
    "NA66",
    "NA67",
    "NA68",
    "NA69",
    "NA70",
    "NA71",
    "NA72",
    "NA73",
    "NA74",
    "NA75",
    "NA76",
    "NA77",
    "NA78",
    "Mushroom Grotto (E)",
    "Coffee Grounds (E)",
    "NA79",
    "Laser Base Alpha (E)",
    "Regifting Zombie",
    "Jack O' Lantern",
    "Leftovers (T)",
    "Turkey Rider",
    "Healthy Treat (T)",
    "Sugary Treat (T)",
    "Trick-or-Treater (G)",
    "Jolly Holly",
    "Mayflower",
    "Red Stinger",
    "Pot of Gold",
    "Corn Dog",
    "Plantern",
    "Spikeweed Sector (E)",
    "Cosmic Nut",
    "Photosynthesizer",
    "Starch-Lord",
    "Gravitree",
    "Force Field (E)",
    "Body Gourd",
    "Pecanolith",
    "Health-Nut",
    "Pear Cub",
    "Grizzly Pear",
    "Garlic",
    "Galacta-Cactus",
    "Invasive Species",
    "Cosmic Mushroom",
    "Lava Guava (E)",
    "Hot Lava (E)",
    "Banana Launcher",
    "Banana Bomb",
    "Astro-Shroom",
    "Sonic Bloom",
    "Molekale",
    "Electric Blueberry",
    "High-Voltage Currant",
    "Blooming Heart",
    "Reincarnation",
    "Sweet Pea",
    "Vegetation Mutation",
    "The Red Plant-It (E)",
    "Cosmic Pea",
    "Banana Peel",
    "Cosmoss",
    "Moonbean",
    "Onion Rings",
    "Captain Cucumber",
    "Clique Peas",
    "Lily of the Valley",
    "Snake Grass",
    "Pod Fighter",
    "Laser Cattail",
    "Leaf Blower",
    "Planet of the Grapes (E)",
    "Cosmic Bean",
    "Mars Flytrap",
    "Sap-Fling (E)",
    "Sappy Place (E)",
    "Cool Bean",
    "Bog of Enlightenment (E)",
    "Shooting Starfruit",
    "Dark Matter Dragonfruit",
    "Melon-Pult",
    "Spyris",
    "Apple-Saucer",
    "Wing-Nut",
    "Venus Flytraplanet (E)",
    "Cosmic Flower",
    "Heartichoke",
    "Banana Split",
    "Half-Banana",
    "Astrocado",
    "Astrocado Pit",
    "Solar Winds (E)",
    "Astro Vera",
    "Tactical Cuke",
    "Sun-Shroom",
    "Toadstool",
    "Haunted Pumpking",
    "Kitchen Sink Zombie",
    "Alien Ooze",
    "Area 22 (E)",
    "Cosmic Yeti",
    "Escape Through Time (T)",
    "Surfer Zombie",
    "Cyborg Zombie",
    "Total Eclipse (E)",
    "Interstellar Bounty Hunter",
    "Supernova Gargantuar",
    "Secret Agent (T)",
    "Synchronized Swimmer",
    "Energy Drink Zombie",
    "Overstuffed Zombie",
    "Cryo-Brain (T)",
    "Moonwalker",
    "Medulla Nebula (E)",
    "Triplication (T)",
    "Cosmic Scientist",
    "Wormhole Gatekeeper",
    "Neutron Imp",
    "Transformation Station (E)",
    "Teleportation Zombie (G)",
    "Interdimensional Zombie",
    "Zombology Teacher",
    "Thinking Cap (T)",
    "Leprechaun Imp",
    "NA80",
    "Disco-Naut",
    "Space Ninja",
    "Meteor Z",
    "Cosmic Dancer",
    "Final Mission (T)",
    "Quasar Wizard",
    "Loose Cannon",
    "Moon Base Z (E)",
    "Binary Stars (G)",
    "Gas Giant",
    "Stupid Cupid",
    "Gargantuar-Throwing Imp",
    "NA81",
    "NA82",
    "Screen Door Zombie (G)",
    "Celestial Custodian",
    "Cone Zone (E)",
    "Cosmic Sports Star",
    "Biodome Botanist",
    "Planetary Gladiator",
    "Going Viral (T)",
    "Black Hole (E)",
    "Intergalactic Warlord",
    "Zombot Battlecruiser 5000 (G)",
    "Defensive End",
    "Genetic Experiment",
    "Gargologist",
    "Ducky Tube Zombie",
    "Ice Pirate (G)",
    "Graveyard (E)",
    "Cosmic Imp",
    "Frosty Mustache (T)",
    "Dr. Spacetime",
    "Space Pirate",
    "Space Cowboy",
    "Cryo-Yeti (G)",
    "Cheese Cutter",
    "Zombie High Diver (G)",
    "Imposter",
    "Trapper Zombie (G)",
    "Fire Rooster",
    "Plucky Clover",
    "Hot Date",
    "Bonus Track Buckethead",
    "Shamrocket",
    "Sportacus",
    "Hippity-Hop Gargantuar",
    "Mystery Egg",
    "Sunnier-Shroom",
    "NA83",
    "Vengeful Cyborg",
    "NA844",
    "NA85",
    "NA86",
    "NA87",
    "NA88",
    "Pair Pearadise (E)",
    "NA89",
    "King of the Grill",
    "Trapper Territory (E)",
    "NA91",
    "NA92",
    "Genetic Amplification",
    "Ensign Uproot",
    "Lieutenant Carrotron",
    "Lightspeed Seed",
    "Terror-Former 10,000",
    "Iron Boarder",
    "Teleportation Station",
    "Ice Moon",
    "NA93",
    "NA94",
    "NA95",
    "NA96",
    "NA97",
    "Hover-Goat 3000",
    "Bad Moon Rising (T)",
    "Imp-Throwing Imp",
    "Forget-Me-Nuts",
    "Atomic Bombegranate",
    "NA98",
    "Go-Nuts",
    "NA99",
    "NA100",
    "Primal Potato Mine",
    "Blockbuster",
    "Grape Responsibility",
    "Three-Nut",
    "Tricarrotops",
    "Imitater",
    "Gloom-Shroom",
    "Umbrella Leaf",
    "Bamboozle",
    "Split Pea",
    "Grape Power",
    "Gatling Pea",
    "Tricorn",
    "Jelly Bean",
    "Lima-Pleurodon",
    "Kernel-pult",
    "Elderberry",
    "Primal Sunflower",
    "Sunflower Seed",
    "Primordial Cheese Shover",
    "Ancient Vimpire",
    "NA101",
    "Extinction Event (T)",
    "Mondo Bronto",
    "Zom-Blob",
    "Parasol Zombie",
    "Gargantuar Mime",
    "Evolutionary Leap (T)",
    "Gizzard Lizard",
    "Quickdraw Con-Man",
    "Zombie Middle Manager",
    "Primeval Yeti",
    "Jurassic Fossilhead",
    "Stompadon",
    "Barrel of Barrels (T)",
    "Blowgun Imp",
    "Cursed Gargolith (G)",
    "Zombot Aerostatic Gondola",
    "Cro-Magnolia",
    "Grave Mistake",
    "Fireweed (E)",
    "Tankylosaurus",
    "Cob Cannon",
    "Transfiguration",
    "Witch Hazel",
    "Ketchup Mechanic",
    "Fraidy Cat",
    "Exploding Fruitcake (T)",
    "Sneezing Zombie",
    "Unexpected Gifts (T)",
    "NA102",
    "Pumpkin Shell",
    "Primal Wall-Nut",
    "Marine Bean",
    "Loco Coco",
    "Shelf Mushroom",
    "Strawberrian",
    "Veloci-Radish Packmate",
    "NA103",
    "Typical Beanstalk",
    "NA104",
    "Pea Patch",
    "Savage Spinach",
    "Apotatosaurus",
    "Primal Peashooter",
    "Lily Pad",
    "Rotobaga",
    "Shrinking Violet",
    "Bird of Paradise",
    "Cross-Pollination",
    "Eyespore",
    "Aloesaurus",
    "Killer Whale",
    "Hunting Grounds (E)",
    "NA105",
    "Gargantuar-Throwing Gargantuar",
    "Mustache Waxer",
    "Quarterly Bonus (T)",
    "Mustache Monument",
    "Duckstache",
    "Zombot Dinotronic Mechasaur",
    "Disco Dance Floor",
    "Zombie's Best Friend",
    "Knockout (T)",
    "Bobblehead",
    "Turquoise Skull Zombie (G)",
    "Lost Colosseum",
    "Grave Robber",
    "Chum Champion",
    "Excavator Zombie (G)",
    "Buried Treasure",
    "Monkey Smuggler (G)",
    "Unthawed Viking",
    "Raiding Raptor",
    "Frankentuar",
    "NA106",
    "Captain Deadbeard",
    "Veloci-Radish Hatchling",
]


def transform_input_to_output(
    input_main_deck: dict, input_supers: dict, name_list: list
) -> list:
    output_lines = []
    graves_dict = {}
    tricks_dict = {}
    environments_dict = {}

    for key, value in input_main_deck.items():
        match = re.match(r"^(\d+)", key)
        x = int(match.group(1)) if match else None
        z = name_list[x - 1] if x and 0 <= x - 1 < len(name_list) else f"z_{key}"

        if "(G)" in z:
            card_name = z.replace("(G)", "")
            graves_dict[card_name] = graves_dict.get(card_name, 0) + value
        if "(T)" in z:
            card_name = z.replace("(T)", "")
            tricks_dict[card_name] = tricks_dict.get(card_name, 0) + value
        if "(E)" in z:
            card_name = z.replace("(E)", "")
            environments_dict[card_name] = environments_dict.get(card_name, 0) + value

        output_lines.append(
            f"{value} {z.replace('(G)', '').replace('(T)', '').replace('(E)', '')}"
        )

    output_lines.insert(0, "#\nBelow is the decoded decklist:")

    if not graves_dict:
        output_lines.append("\n##\n[No graves]")
    else:
        output_lines.append("\n##\n(Zombies Only) All Graves:")
        for name, count in graves_dict.items():
            output_lines.append(f"{count} {name}")

    if not tricks_dict:
        output_lines.append("\n##\n[No tricks]")
    else:
        output_lines.append("\n##\n(Zombies Only) All Tricks:")
        for name, count in tricks_dict.items():
            output_lines.append(f"{count} {name}")

    if not environments_dict:
        output_lines.append("\n##\n[No environments]")
    else:
        output_lines.append("\n##\nAll Environments:")
        for name, count in environments_dict.items():
            output_lines.append(f"{count} {name}")

    output_lines.append("\n##\nSuperpowers:")
    for key in input_supers.keys():
        match = re.match(r"^(\d+)", key)
        x = int(match.group(1)) if match else None
        z = name_list[x - 1] if x and 0 <= x - 1 < len(name_list) else f"z_{key}"

        output_lines.append(z)

    return output_lines


def get_decks_from_raw_input(raw_input: dict) -> tuple[dict, dict]:
    sd_obj = json.loads(raw_input["sd"])
    main_deck = sd_obj["Deck"]["main"]
    supers = sd_obj["Deck"]["super"]

    return main_deck, supers


raw_input = {
  "ty": "MatchReady",
  "sd": "{\"PlayerId\":\"1007494849412\",\"DeckId\":\"ceef8cec-02a6-4608-933d-c898be604dc2\",\"HeroId\":\"Rose\",\"HeroAssetId\":\"Prefabs/Heroes/Rose\",\"Faction\":\"Plants\",\"PlayerName\":\"Dhymbot\",\"RankLastSeason\":30,\"CanMulligan\":true,\"TrackingSamplingKey\":0.307463854551315,\"IsTracked\":true,\"Deck\":{\"main\":{\"142\":1,\"470\":4,\"446\":4,\"455\":4,\"456\":4,\"476\":2,\"555\":2,\"469\":2,\"346\":2,\"46\":1,\"151\":2,\"7\":2,\"11\":3,\"150\":3,\"157\":2,\"160\":2},\"super\":{\"262\":1,\"146\":1,\"135\":1,\"47\":1}}}",
  "gi": "ef05c46f-f90b-4632-99a7-9f88b594915f",
  "or": 14
}
input_main_deck, input_supers = get_decks_from_raw_input(raw_input)
output_lines = transform_input_to_output(input_main_deck, input_supers, name_list)
print(*output_lines, sep="\n")
